/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lexicon_airway;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author User
 */
public class Main_screen extends javax.swing.JFrame
{

    static final int FIRSTCLASS = 1;
    static final int ECONOMYCLASS = 2;

    static final int FIRSTCLASSPRICE = 20000;
    static final int ECONOMYCLASSPRICE = 5000;

    String admin = "";

    Logic logic = new Logic();
    int totalPris = 0;
    int classTotal = FIRSTCLASSPRICE;
    int foodTotal = 0;
    int drinkTotal = 0;
    DefaultListModel<Airplane> planeListArray = new DefaultListModel();

    DefaultListModel<Food> foodListArrayFirstClass = new DefaultListModel();
    DefaultListModel<Food> foodListArrayEcoClass = new DefaultListModel();

    DefaultListModel<Food> drinkListArrayFirstClass = new DefaultListModel();
    DefaultListModel<Food> drinkListArrayEcoClass = new DefaultListModel();

    /**
     * Creates new form Main_screen
     */
    public Main_screen()
    {
        initComponents();
        fill();
        planeList.setModel(planeListArray);
        drinkList.setModel(drinkListArrayEcoClass);
        foodList.setModel(foodListArrayEcoClass);
        foodList.setVisible(false);
        drinkList.setVisible(false);
        AdminButton.setVisible(false);
        AdminPlaneTab.setVisible(false);
        TabbedPane.remove(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        planeScrollPane = new javax.swing.JScrollPane();
        planeList = new javax.swing.JList<>();
        searchButton = new javax.swing.JTextField();
        planeListLockButton = new javax.swing.JButton();
        TabbedPane = new javax.swing.JTabbedPane();
        loginPassanger = new javax.swing.JPanel();
        AdminButton = new javax.swing.JButton();
        newPassangerPanel = new javax.swing.JPanel();
        ClassLabel = new javax.swing.JLabel();
        prisListLabel = new javax.swing.JLabel();
        flightOptionsLabel = new javax.swing.JLabel();
        classPrisLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        foodList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        drinkList = new javax.swing.JList<>();
        foodCheck = new javax.swing.JCheckBox();
        drinkCheck = new javax.swing.JCheckBox();
        classCheck = new javax.swing.JCheckBox();
        foodTotalLabel = new javax.swing.JLabel();
        prisTotalLabel = new javax.swing.JLabel();
        passangerLabel = new javax.swing.JLabel();
        yourNameInput = new javax.swing.JTextField();
        bookButton = new javax.swing.JButton();
        AdminPlaneTab = new javax.swing.JPanel();
        planeComboBox = new javax.swing.JComboBox<>();
        passangerInPlanePane = new javax.swing.JScrollPane();
        passangerInPlaneList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        planeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        planeList.setCellRenderer(new planeCellRenderer());
        planeList.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                planeListKeyTyped(evt);
            }
        });
        planeScrollPane.setViewportView(planeList);

        searchButton.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                searchButtonFocusGained(evt);
            }
        });

        planeListLockButton.setText("Lock");

        AdminButton.setText("Admin");
        AdminButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPassangerLayout = new javax.swing.GroupLayout(loginPassanger);
        loginPassanger.setLayout(loginPassangerLayout);
        loginPassangerLayout.setHorizontalGroup(
            loginPassangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPassangerLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(AdminButton)
                .addContainerGap())
        );
        loginPassangerLayout.setVerticalGroup(
            loginPassangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPassangerLayout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addComponent(AdminButton)
                .addContainerGap())
        );

        TabbedPane.addTab("Login", loginPassanger);

        ClassLabel.setText("Class");

        prisListLabel.setText("Pris");

        flightOptionsLabel.setText("Selections");

        classPrisLabel.setText("5000");

        foodList.setCellRenderer(new foodCellRenderer());
        foodList.setEnabled(false);
        foodList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                foodListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(foodList);

        drinkList.setCellRenderer(new foodCellRenderer());
        drinkList.setEnabled(false);
        drinkList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                drinkListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(drinkList);

        foodCheck.setBackground(new java.awt.Color(255, 255, 255));
        foodCheck.setText("Food");
        foodCheck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                foodCheckActionPerformed(evt);
            }
        });

        drinkCheck.setBackground(new java.awt.Color(255, 255, 255));
        drinkCheck.setText("Drink");
        drinkCheck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                drinkCheckActionPerformed(evt);
            }
        });

        classCheck.setBackground(new java.awt.Color(255, 255, 255));
        classCheck.setText("First Class");
        classCheck.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                classCheckActionPerformed(evt);
            }
        });

        foodTotalLabel.setText("0");

        prisTotalLabel.setText("5000");

        passangerLabel.setText("Your Name");

        bookButton.setText("Book");
        bookButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newPassangerPanelLayout = new javax.swing.GroupLayout(newPassangerPanel);
        newPassangerPanel.setLayout(newPassangerPanelLayout);
        newPassangerPanelLayout.setHorizontalGroup(
            newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPassangerPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPassangerPanelLayout.createSequentialGroup()
                        .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flightOptionsLabel)
                            .addGroup(newPassangerPanelLayout.createSequentialGroup()
                                .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foodCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(drinkCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(newPassangerPanelLayout.createSequentialGroup()
                                .addComponent(ClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(classCheck)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prisTotalLabel)
                            .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prisListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(classPrisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(foodTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(newPassangerPanelLayout.createSequentialGroup()
                        .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passangerLabel)
                            .addComponent(yourNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newPassangerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        newPassangerPanelLayout.setVerticalGroup(
            newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newPassangerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prisListLabel)
                    .addComponent(flightOptionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassLabel)
                    .addComponent(classPrisLabel)
                    .addComponent(classCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foodCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinkCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPassangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(foodTotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passangerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yourNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prisTotalLabel)
                .addGap(18, 18, 18)
                .addComponent(bookButton)
                .addGap(14, 14, 14))
        );

        TabbedPane.addTab("New", newPassangerPanel);

        passangerInPlaneList.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        passangerInPlanePane.setViewportView(passangerInPlaneList);

        javax.swing.GroupLayout AdminPlaneTabLayout = new javax.swing.GroupLayout(AdminPlaneTab);
        AdminPlaneTab.setLayout(AdminPlaneTabLayout);
        AdminPlaneTabLayout.setHorizontalGroup(
            AdminPlaneTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPlaneTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passangerInPlanePane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        AdminPlaneTabLayout.setVerticalGroup(
            AdminPlaneTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPlaneTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPlaneTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passangerInPlanePane, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addGroup(AdminPlaneTabLayout.createSequentialGroup()
                        .addComponent(planeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        TabbedPane.addTab("Planes", AdminPlaneTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(planeListLockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(planeScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(planeListLockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void planeListKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_planeListKeyTyped
    {//GEN-HEADEREND:event_planeListKeyTyped
        System.out.println(evt.getKeyChar());
        admin = admin + evt.getKeyChar();
        if (admin.equals("admin"))
        {
            AdminButton.setVisible(true);
        }
    }//GEN-LAST:event_planeListKeyTyped

    private void searchButtonFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_searchButtonFocusGained
    {//GEN-HEADEREND:event_searchButtonFocusGained
        admin = "";
    }//GEN-LAST:event_searchButtonFocusGained

    private void foodListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_foodListValueChanged
    {//GEN-HEADEREND:event_foodListValueChanged
         if (foodList.getSelectedIndex() >= 0)
        {
            int tempPrice = 0;
            for (int i = 0; i < foodList.getSelectedIndices().length; i++)
            {
                tempPrice = tempPrice + rankListReturner(false).get(foodList.getSelectedIndices()[i]).getPrice();

            }
            foodTotal = tempPrice;
            calculateTotal();
        }
    }//GEN-LAST:event_foodListValueChanged

    private void drinkListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_drinkListValueChanged
    {//GEN-HEADEREND:event_drinkListValueChanged
        if (drinkList.getSelectedIndex() >= 0)
        {
            int tempPrice = 0;
            for (int i = 0; i < drinkList.getSelectedIndices().length; i++)
            {
                tempPrice = tempPrice + rankListReturner(true).get(drinkList.getSelectedIndices()[i]).getPrice();

            }
            drinkTotal = tempPrice;
            calculateTotal();
        }
    }//GEN-LAST:event_drinkListValueChanged

    private void foodCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_foodCheckActionPerformed
    {//GEN-HEADEREND:event_foodCheckActionPerformed
        if (foodCheck.isSelected())
        {
            foodList.setVisible(true);
            foodList.setEnabled(true);
            foodList.setSelectedIndex(0);
            foodTotal = rankListReturner(false).get(foodList.getSelectedIndex()).getPrice();
        } else
        {
            foodList.setVisible(false);
            foodList.setEnabled(false);
            foodTotal = 0;
            foodList.clearSelection();

        }
        calculateTotal();
    }//GEN-LAST:event_foodCheckActionPerformed

    private void drinkCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_drinkCheckActionPerformed
    {//GEN-HEADEREND:event_drinkCheckActionPerformed
        if (drinkCheck.isSelected())
        {
            drinkList.setEnabled(true);
            drinkList.setVisible(true);
            drinkList.setSelectedIndex(0);
            drinkTotal = rankListReturner(true).get(drinkList.getSelectedIndex()).getPrice();
        } else
        {
            drinkList.setEnabled(false);
            drinkList.setVisible(false);
            drinkTotal = 0;
            drinkList.clearSelection();
        }
        calculateTotal();
    }//GEN-LAST:event_drinkCheckActionPerformed

    private void classCheckActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_classCheckActionPerformed
    {//GEN-HEADEREND:event_classCheckActionPerformed
        if (classCheck.isSelected())
        {
            classPrisLabel.setText("" + FIRSTCLASSPRICE);
            classTotal = FIRSTCLASSPRICE;
            foodList.setModel(foodListArrayFirstClass);
            drinkList.setModel(drinkListArrayFirstClass);
            foodList.clearSelection();
            drinkList.clearSelection();
        } else
        {
            classPrisLabel.setText("" + ECONOMYCLASSPRICE);
            classTotal = ECONOMYCLASSPRICE;
            foodList.setModel(foodListArrayEcoClass);
            drinkList.setModel(drinkListArrayEcoClass);
            foodList.clearSelection();
            drinkList.clearSelection();
        }
        calculateTotal();
    }//GEN-LAST:event_classCheckActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bookButtonActionPerformed
    {//GEN-HEADEREND:event_bookButtonActionPerformed
        Passanger pass = logic.createPassanger(yourNameInput.getText());
        Airplane plane = planeListArray.getElementAt(planeList.getSelectedIndex());  
        ArrayList<Food> food = new ArrayList<>();
        food.addAll(drinkList.getSelectedValuesList());
        food.addAll(foodList.getSelectedValuesList());
        
        int rank = ECONOMYCLASS;
        if(classCheck.isSelected()) {
            rank = FIRSTCLASS;
        }
        
        logic.bookTicket(plane, pass, rank, food);
        planeList.clearSelection();
    }//GEN-LAST:event_bookButtonActionPerformed

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AdminButtonActionPerformed
    {//GEN-HEADEREND:event_AdminButtonActionPerformed
        TabbedPane.add(AdminPlaneTab);
        TabbedPane.setTitleAt(2, "Planes");
    }//GEN-LAST:event_AdminButtonActionPerformed

    class planeCellRenderer extends JLabel implements ListCellRenderer
    {

        private final Color HIGHLIGHT_COLOR = new Color(0, 0, 128);

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus)
        {
            Airplane entry = (Airplane) value;
            setText(" " + entry.getCallsign() + " : " + entry.getAvEco() + " : " + entry.getAvFirst());
            setIcon(null);
            if (isSelected)
            {
//                setBackground(Color.GRAY);
                setForeground(HIGHLIGHT_COLOR);
            } else
            {
//                setBackground(list.getBackground());
                setForeground(Color.BLACK);
            }

            return this;
        }

    }

    class foodCellRenderer extends JLabel implements ListCellRenderer
    {

        private final Color HIGHLIGHT_COLOR = new Color(0, 0, 128);

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus)
        {
            Food entry = (Food) value;
            setText(" " + entry.getName() + " Pris: " + entry.getPrice());
            setIcon(null);
            if (isSelected)
            {
//                setBackground(Color.GRAY);
                setForeground(HIGHLIGHT_COLOR);
            } else
            {
//                setBackground(Color.BLACK);
                setForeground(Color.BLACK);
            }

            return this;
        }

    }

    public DefaultListModel<Food> rankListReturner(boolean isDrink)
    {
        if (isDrink == false)
        {
            if (classCheck.isSelected())
            {
                return foodListArrayFirstClass;
            } else
            {
                return foodListArrayEcoClass;
            }
        } else if (classCheck.isSelected())
        {
            return drinkListArrayFirstClass;
        } else
        {
            return drinkListArrayEcoClass;
        }
    }

    public void calculateTotal()
    {
        totalPris = foodTotal + drinkTotal + classTotal;
        int temp = foodTotal + drinkTotal;
        foodTotalLabel.setText("" + temp);
        prisTotalLabel.setText("" + totalPris);
    }

    public final void fill()
    {
        logic.db.HangerDatabase.stream().forEach((item)
                -> 
                {
                    planeListArray.addElement(item);
        });

        logic.db.FoodMenu.stream().forEach((item)
                -> 
                {
                    if (item.getRank() == FIRSTCLASS)
                    {
                        if (item.getIsDrink())
                        {
                            drinkListArrayFirstClass.addElement(item);
                        } else
                        {
                            foodListArrayFirstClass.addElement(item);
                        }
                    } else if (item.getIsDrink())
                    {
                        drinkListArrayEcoClass.addElement(item);
                    } else
                    {
                        foodListArrayEcoClass.addElement(item);
                    }
        });

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Main_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButton;
    private javax.swing.JPanel AdminPlaneTab;
    private javax.swing.JLabel ClassLabel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton bookButton;
    private javax.swing.JCheckBox classCheck;
    private javax.swing.JLabel classPrisLabel;
    private javax.swing.JCheckBox drinkCheck;
    private javax.swing.JList<Food> drinkList;
    private javax.swing.JLabel flightOptionsLabel;
    private javax.swing.JCheckBox foodCheck;
    private javax.swing.JList<Food> foodList;
    private javax.swing.JLabel foodTotalLabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel loginPassanger;
    private javax.swing.JPanel newPassangerPanel;
    private javax.swing.JList<String> passangerInPlaneList;
    private javax.swing.JScrollPane passangerInPlanePane;
    private javax.swing.JLabel passangerLabel;
    private javax.swing.JComboBox<String> planeComboBox;
    private javax.swing.JList<Airplane> planeList;
    private javax.swing.JButton planeListLockButton;
    private javax.swing.JScrollPane planeScrollPane;
    private javax.swing.JLabel prisListLabel;
    private javax.swing.JLabel prisTotalLabel;
    private javax.swing.JTextField searchButton;
    private javax.swing.JTextField yourNameInput;
    // End of variables declaration//GEN-END:variables
}
